server:
  port: ${shopping-mall.server.port}

spring:
  profiles:
    active: prod
  application:
    name: ShoppingMall-Backend
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:    jdbc:mysql://${shopping-mall.db.host}:${shopping-mall.db.port}/shopping_mall?rewriteBatchedStatements=true&autoReconnect=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
    username: ${shopping-mall.db.username}
    password: ${shopping-mall.db.password}
    druid:
      test-on-borrow: true  # 借用连接时测试其有效性
      test-while-idle: true  # 空闲时测试连接
      validation-query: SELECT 1  # 验证查询语句
      time-between-eviction-runs-millis: 60000  # 连接池扫描间隔时间（毫秒）
      min-evictable-idle-time-millis: 300000  # 连接最小空闲时间（毫秒）
      max-active: 20  # 最大连接数
      min-idle: 5  # 最小连接数
      max-wait: 60000  # 获取连接最大等待时间（毫秒）
      validation-query-timeout: 5000  # 验证查询超时时间（毫秒）
  data:
    redis:
      host: ${shopping-mall.redis.host}
      port: ${shopping-mall.redis.port}
      password: ${shopping-mall.redis.password}
      database: ${shopping-mall.redis.database}
  transaction:
    rollback-on-commit-failure: true

email:
  user: 18702099658@163.com
  code: KKgbV39XUf8c5iL9
  host: smtp.163.com
  auth: true

mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
